GET http://localhost:80/api/item?id=99
Accept: application/json

###
// The request body is provided in place
POST http://localhost:8000/api/vet/register HTTP/1.1
Content-Type: application/json
## Cookie: key=first-value

{
    "first_name": "ga" ,
    "last_name" :  "elle",
    "email" :  "eee@eee.ee",
    "password" : "kjiji",
    "phone_number" : "hu;",
    "siret":  "ljh"
}
